name: genomedecoder
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - repeatmasker==4.1.5
  - pip:
      - cigar==0.1.3
      - pandas==2.2.2
      - biopython==1.81
      - psutil==5.9.0